"""Add LLM config columns

Revision ID: 2be45c711a79
Revises: 
Create Date: 2026-02-13 12:28:17.898808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be45c711a79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('deployments')
    # op.alter_column('architectures', 'intent_json',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'graph_json',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=False)
    # op.alter_column('architectures', 'terraform_files_json',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'cost_json',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'visual_json',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    op.add_column('users', sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('llm_preferences', sa.JSON(), nullable=True))
    # op.alter_column('users', 'preferences',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'preferences',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.drop_column('users', 'llm_preferences')
    op.drop_column('users', 'llm_api_key_encrypted')
    # op.alter_column('architectures', 'visual_json',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'cost_json',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'terraform_files_json',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('architectures', 'graph_json',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)
    # op.alter_column('architectures', 'intent_json',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.create_table('deployments',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('project_id', sa.INTEGER(), nullable=False),
    # sa.Column('architecture_version', sa.INTEGER(), nullable=False),
    # sa.Column('action', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    # sa.Column('logs', sa.TEXT(), nullable=True),
    # sa.Column('error_message', sa.TEXT(), nullable=True),
    # sa.Column('started_at', sa.DATETIME(), nullable=True),
    # sa.Column('completed_at', sa.DATETIME(), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
